### ISSUE TITLE
Add text below cube picture

### ISSUE THREAD

**Issue by avelytchko** [roudai/VisualCubeEditor2#2]
Hi. Thanks for great project. Is it possible to add small feature? Ability to add text of moves (notation) below cube picture? It will be really useful to build algorithms map.
<img width="183" alt="Screen Shot 2023-11-05 at 16 03 02" src="https://github.com/roudai/VisualCubeEditor2/assets/919635/db3e13fd-ca9f-4b29-9f48-f3dc7f8701c7">

**Comment by roudai** [comment]
Thank you for your good suggestion.
We are relying on another project (VisualCube TS) to create the images, so adding text as images will require modifications to that project.
I can do quickly If I just display the text below the image,  but would that be satisfactory?

**Comment by avelytchko** [comment]
Adding text to images is not necessary. Just adding text below the image will be enough. Appreciated your prompt response.

**Comment by roudai** [comment]
Algorithm values are now displayed below the image.
Also, added "(" and ")" to the Add Algorithm button.

**Comment by avelytchko** [comment]
Amazing, thank you!
